// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znaudzagtjcuqpxaybmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuYXVkemFndGpjdXFweGF5Ym12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3ODU3MzQsImV4cCI6MjA4NjM2MTczNH0.lBVnye-WfGlHQ2zSXsfFFXGJ6O9Rm8rYh31WWTGSvWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});