// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyzgrpishdhyvjerhcao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5emdycGlzaGRoeXZqZXJoY2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1MzUyMTQsImV4cCI6MjA5NTExMTIxNH0.04gCKkdP5vFg6SyhovkFAPcGOYoFAyznk9pFiJl9iAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
